spring.application.name=TOW
spring.mongodb.uri=mongodb+srv://bindranimar2_db_user:orfw1xamZGBAGHqA@cluster0.gdvh55t.mongodb.net/ThaparOnWheels?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong!
